### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by ghost** [blang/thymer#1]
can't load package: package https:/github.com/blang/thymer: cannot find package "https:/github.com/blang/thymer" in any of:                        
        /usr/lib/go/src/https:/github.com/blang/thymer (from $GOROOT)    
        /home/garo/go/src/https:/github.com/blang/thymer (from $GOPATH)

**Comment by blang** [comment]
Works for me, but for now please try:
```
go get github.com/blang/thymer
```
You can find the executable in $GOPATH/bin/thymer
